[package]
name = "fhedb-server"
version = "0.1.0"
edition = "2024"

[dependencies]
fhedb-core = { path = "../fhedb-core" }
fhedb-query = { path = "../fhedb-query" }
fhedb-types = { path = "../fhedb-types" }

axum = "^0.8.8"
tokio = { version = "1.52.0", features = ["full"] }
dirs = "6.0.0"
serde = "1.0.228"
serde-saphyr = "0.0.23"
serde_json = "1.0.149"
fern = "0.7.1"
thiserror = { workspace = true }
log = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
bson = { workspace = true, features = ["serde"] }
